apiVersion: apps/v1
kind: Deployment
metadata:
  name: api
  namespace: default
spec:
  replicas: 1

  selector:
    matchLabels:
      name: api
  template:
    metadata:
      labels:
        name: api
    spec:
      serviceAccountName: docker-sa
      containers:
        - name: api
          image: zhaoyi0113/rancher-go-api
          ports:
            - containerPort: 80