apiVersion: v1
kind: Service
metadata:
  name: api
  annotation:
    cloud.google.com/neg: '{"ingress": true}'
spec:
  selector:
    name: api
  ports:
    - port: 80
      targetPort: 8080
      protocol: TCP
  type: NodePort
